// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { CreateNodeData, CreateNodeResponses, ExchangeTokenData, ExchangeTokenResponses, GetCurrentNodeData, GetCurrentNodeResponses, GetCurrentUserData, GetCurrentUserResponses, RefreshTokenData, RefreshTokenResponses, ResetNodeTokenData, ResetNodeTokenResponses, RevokeAllRefreshTokensData, RevokeAllRefreshTokensResponses, RevokeRefreshTokenData, RevokeRefreshTokenResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const exchangeToken = <ThrowOnError extends boolean = true>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => options.client.post<ExchangeTokenResponses, unknown, ThrowOnError>({
    url: '/auth/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const refreshToken = <ThrowOnError extends boolean = true>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revokeRefreshToken = <ThrowOnError extends boolean = true>(options: Options<RevokeRefreshTokenData, ThrowOnError>): RequestResult<RevokeRefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RevokeRefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const revokeAllRefreshTokens = <ThrowOnError extends boolean = true>(options: Options<RevokeAllRefreshTokensData, ThrowOnError>): RequestResult<RevokeAllRefreshTokensResponses, unknown, ThrowOnError> => options.client.post<RevokeAllRefreshTokensResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/auth/revoke-all',
    ...options
});

/**
 * Get the current user
 */
export const getCurrentUser = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/users/me',
    ...options
});

/**
 * Create a new render node
 */
export const createNode = <ThrowOnError extends boolean = true>(options: Options<CreateNodeData, ThrowOnError>): RequestResult<CreateNodeResponses, unknown, ThrowOnError> => options.client.post<CreateNodeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset the authentication token of a render node
 */
export const resetNodeToken = <ThrowOnError extends boolean = true>(options: Options<ResetNodeTokenData, ThrowOnError>): RequestResult<ResetNodeTokenResponses, unknown, ThrowOnError> => options.client.post<ResetNodeTokenResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/{id}/reset-token',
    ...options
});

/**
 * Get the current render node
 */
export const getCurrentNode = <ThrowOnError extends boolean = true>(options: Options<GetCurrentNodeData, ThrowOnError>): RequestResult<GetCurrentNodeResponses, unknown, ThrowOnError> => options.client.get<GetCurrentNodeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'node-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me',
    ...options
});
