// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import type { CreateJobData, CreateJobResponses, CreateNodeData, CreateNodeResponses, ExchangeTokenData, ExchangeTokenResponses, FinishTaskData, FinishTaskErrors, FinishTaskRenderingData, FinishTaskRenderingErrors, FinishTaskRenderingResponses, FinishTaskResponses, GetCurrentNodeData, GetCurrentNodeResponses, GetCurrentUserData, GetCurrentUserNodesData, GetCurrentUserNodesResponses, GetCurrentUserResponses, GetJobFileData, GetJobFileErrors, GetJobFileResponses, GetNextTaskData, GetNextTaskResponses, RefreshTokenData, RefreshTokenResponses, ResetNodeTokenData, ResetNodeTokenResponses, RevokeAllRefreshTokensData, RevokeAllRefreshTokensResponses, RevokeRefreshTokenData, RevokeRefreshTokenResponses, StartJobData, StartJobErrors, StartJobResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create refresh and access tokens from an auth code
 */
export const exchangeToken = <ThrowOnError extends boolean = true>(options: Options<ExchangeTokenData, ThrowOnError>): RequestResult<ExchangeTokenResponses, unknown, ThrowOnError> => options.client.post<ExchangeTokenResponses, unknown, ThrowOnError>({
    url: '/auth/exchange',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get a new access token
 *
 * This creates a new short-lived access token. The refresh token will be rotated and a new refresh token is returned, too.
 */
export const refreshToken = <ThrowOnError extends boolean = true>(options: Options<RefreshTokenData, ThrowOnError>): RequestResult<RefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/refresh',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke a refresh token
 *
 * This revokes the specified refresh token. Access tokens generated by this refresh token will continue to work until they expire.
 */
export const revokeRefreshToken = <ThrowOnError extends boolean = true>(options: Options<RevokeRefreshTokenData, ThrowOnError>): RequestResult<RevokeRefreshTokenResponses, unknown, ThrowOnError> => options.client.post<RevokeRefreshTokenResponses, unknown, ThrowOnError>({
    url: '/auth/revoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke all refresh tokens
 *
 * This revokes all refresh token of the current user. All access tokens generated before will continue to work until they expire.
 */
export const revokeAllRefreshTokens = <ThrowOnError extends boolean = true>(options: Options<RevokeAllRefreshTokensData, ThrowOnError>): RequestResult<RevokeAllRefreshTokensResponses, unknown, ThrowOnError> => options.client.post<RevokeAllRefreshTokensResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/auth/revoke-all',
    ...options
});

/**
 * Get the current user
 */
export const getCurrentUser = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserData, ThrowOnError>): RequestResult<GetCurrentUserResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/users/me',
    ...options
});

/**
 * Get the render nodes of the current user
 */
export const getCurrentUserNodes = <ThrowOnError extends boolean = true>(options: Options<GetCurrentUserNodesData, ThrowOnError>): RequestResult<GetCurrentUserNodesResponses, unknown, ThrowOnError> => options.client.get<GetCurrentUserNodesResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/users/me/nodes',
    ...options
});

/**
 * Create a new render node
 */
export const createNode = <ThrowOnError extends boolean = true>(options: Options<CreateNodeData, ThrowOnError>): RequestResult<CreateNodeResponses, unknown, ThrowOnError> => options.client.post<CreateNodeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Reset the authentication token of a render node
 */
export const resetNodeToken = <ThrowOnError extends boolean = true>(options: Options<ResetNodeTokenData, ThrowOnError>): RequestResult<ResetNodeTokenResponses, unknown, ThrowOnError> => options.client.post<ResetNodeTokenResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/{id}/reset-token',
    ...options
});

/**
 * Get the current render node
 */
export const getCurrentNode = <ThrowOnError extends boolean = true>(options: Options<GetCurrentNodeData, ThrowOnError>): RequestResult<GetCurrentNodeResponses, unknown, ThrowOnError> => options.client.get<GetCurrentNodeResponses, unknown, ThrowOnError>({
    security: [{
            key: 'node-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me',
    ...options
});

/**
 * Get the next task for this node
 */
export const getNextTask = <ThrowOnError extends boolean = true>(options: Options<GetNextTaskData, ThrowOnError>): RequestResult<GetNextTaskResponses, unknown, ThrowOnError> => options.client.get<GetNextTaskResponses, unknown, ThrowOnError>({
    security: [{
            key: 'node-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/next',
    ...options
});

/**
 * Get result upload URLs and mark the task as uploading
 */
export const finishTaskRendering = <ThrowOnError extends boolean = true>(options: Options<FinishTaskRenderingData, ThrowOnError>): RequestResult<FinishTaskRenderingResponses, FinishTaskRenderingErrors, ThrowOnError> => options.client.post<FinishTaskRenderingResponses, FinishTaskRenderingErrors, ThrowOnError>({
    security: [{
            key: 'node-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/{id}/upload',
    ...options
});

/**
 * Mark the task as completed after uploading the results
 */
export const finishTask = <ThrowOnError extends boolean = true>(options: Options<FinishTaskData, ThrowOnError>): RequestResult<FinishTaskResponses, FinishTaskErrors, ThrowOnError> => options.client.post<FinishTaskResponses, FinishTaskErrors, ThrowOnError>({
    security: [{
            key: 'node-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/nodes/me/tasks/{id}/finish',
    ...options
});

/**
 * Create a render job
 */
export const createJob = <ThrowOnError extends boolean = true>(options: Options<CreateJobData, ThrowOnError>): RequestResult<CreateJobResponses, unknown, ThrowOnError> => options.client.post<CreateJobResponses, unknown, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/jobs',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Start a render job
 *
 * Call this after all required files have been uploaded
 */
export const startJob = <ThrowOnError extends boolean = true>(options: Options<StartJobData, ThrowOnError>): RequestResult<StartJobResponses, StartJobErrors, ThrowOnError> => options.client.post<StartJobResponses, StartJobErrors, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/jobs/{id}/start',
    ...options
});

/**
 * Download scene files of a job
 */
export const getJobFile = <ThrowOnError extends boolean = true>(options: Options<GetJobFileData, ThrowOnError>): RequestResult<GetJobFileResponses, GetJobFileErrors, ThrowOnError> => options.client.get<GetJobFileResponses, GetJobFileErrors, ThrowOnError>({
    security: [{
            key: 'access-token',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/jobs/{id}/files/{file}',
    ...options
});
