// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuthenticateDto = {
    code: string;
};

export type TokenResponseDto = {
    refreshToken: {
        expiresAt: string;
        token: string;
    };
    accessToken: string;
};

export type RefreshTokenDto = {
    refreshToken: string;
};

export type UserResponseDto = {
    id: number;
    displayName: string;
};

export type CreateNodeDto = {
    name?: string;
};

export type CreateNodeResponse = {
    id: number;
    /**
     * Render node token (can not be retrieved again later)
     */
    token: string;
};

export type ResetNodeTokenResponse = {
    /**
     * New render node token (can not be retrieved again later)
     */
    token: string;
};

export type ExchangeTokenData = {
    body: AuthenticateDto;
    path?: never;
    query?: never;
    url: '/auth/exchange';
};

export type ExchangeTokenResponses = {
    201: TokenResponseDto;
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type RefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenResponses = {
    201: TokenResponseDto;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type RevokeRefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/revoke';
};

export type RevokeRefreshTokenResponses = {
    204: void;
};

export type RevokeRefreshTokenResponse = RevokeRefreshTokenResponses[keyof RevokeRefreshTokenResponses];

export type RevokeAllRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/revoke-all';
};

export type RevokeAllRefreshTokensResponses = {
    204: void;
};

export type RevokeAllRefreshTokensResponse = RevokeAllRefreshTokensResponses[keyof RevokeAllRefreshTokensResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserResponses = {
    200: UserResponseDto;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type CreateNodeData = {
    body: CreateNodeDto;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type CreateNodeResponses = {
    201: CreateNodeResponse;
};

export type CreateNodeResponse2 = CreateNodeResponses[keyof CreateNodeResponses];

export type ResetNodeTokenData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/{id}/reset-token';
};

export type ResetNodeTokenResponses = {
    200: ResetNodeTokenResponse;
};

export type ResetNodeTokenResponse2 = ResetNodeTokenResponses[keyof ResetNodeTokenResponses];

export type GetCurrentNodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me';
};

export type GetCurrentNodeResponses = {
    200: unknown;
};
