// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type AuthenticateDto = {
    code: string;
};

export type TokenResponse = {
    refreshToken: {
        expiresAt: string;
        token: string;
    };
    accessToken: string;
};

export type RefreshTokenDto = {
    refreshToken: string;
};

export type UserResponse = {
    id: number;
    displayName: string;
    avatarUrl?: {
        [key: string]: unknown;
    };
};

export type UserNodeResponse = {
    id: number;
    name?: string;
    lastSeenAt?: string;
};

export type JobStatus = 'draft' | 'queued' | 'running' | 'completed' | 'aborted';

export type Order = 'asc' | 'desc';

export type UserJob = {
    id: number;
    status: JobStatus;
    progress: number;
    spp: number;
    width: number;
    height: number;
    hasEmitterGrid: boolean;
    createDump: boolean;
    createdAt: string;
    startedAt?: string;
    finishedAt?: string;
    abortedAt?: string;
};

export type CurrentPage = {
    page: number;
    size: number;
};

export type PaginationInfo = {
    page: CurrentPage;
    totalCount: number;
};

export type UserJobsResponse = {
    data: Array<UserJob>;
    extra: PaginationInfo;
};

export type CreateNodeDto = {
    name?: string;
};

export type CreateNodeResponse = {
    id: number;
    /**
     * Render node token (can not be retrieved again later)
     */
    token: string;
};

export type ResetNodeTokenResponse = {
    /**
     * New render node token (can not be retrieved again later)
     */
    token: string;
};

export type RenderNodeResponse = {
    id: number;
    name?: string;
    enabled: boolean;
    lastSeenAt: string;
    createdAt: string;
    updatedAt: string;
};

export type NextTaskResponse = {
    id: number;
    job: {
        id: number;
        width: number;
        height: number;
    };
    spp: number;
    tile: {
        x: number;
        y: number;
        width: number;
        height: number;
    };
    files: {
        scene: {
            url: string;
        };
        octree: {
            url: string;
        };
        emittergrid?: {
            url: string;
        };
        resourcePacks: Array<{
            id: number;
            url: string;
        }>;
    };
};

export type FinishTaskRenderingResponse = {
    uploadUrls: {
        image: string;
        dump?: string;
    };
};

export type ReportTaskProgressDto = {
    spp: number;
};

export type ResourcePackDto = {
    /**
     * Resource pack ID
     */
    id: number;
};

export type CreateJobDto = {
    spp: number;
    width: number;
    height: number;
    createDump?: boolean;
    resourcePacks: Array<ResourcePackDto>;
};

export type CreateJobResponse = {
    id: number;
    uploadUrls: {
        scene: string;
        octree: string;
        emittergrid: string;
    };
};

export type UrlResponse = {
    url: string;
};

export type TileResponse = {
    /**
     * Horizontal position of the tile in pixels
     */
    x: number;
    /**
     * Vertical position of the tile in pixels
     */
    y: number;
    /**
     * Width of the tile in pixels
     */
    width: number;
    /**
     * Height of the tile in pixels
     */
    height: number;
    /**
     * Rendering progress of the tile
     */
    progress: number;
    /**
     * URL to access the rendered tile image in PNG format. The URL is guaranteed to remain valid for at least one hour after it is requested.
     */
    url?: string;
};

export type ResourcePackResponse = {
    /**
     * The ID of this resource pack that can be used when creating a render job
     */
    id: number;
    /**
     * The name of this resource pack
     */
    name: string;
    /**
     * A description of this resource pack
     */
    description?: string;
};

export type ExchangeTokenData = {
    body: AuthenticateDto;
    path?: never;
    query?: never;
    url: '/auth/exchange';
};

export type ExchangeTokenResponses = {
    201: TokenResponse;
};

export type ExchangeTokenResponse = ExchangeTokenResponses[keyof ExchangeTokenResponses];

export type RefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshTokenResponses = {
    201: TokenResponse;
};

export type RefreshTokenResponse = RefreshTokenResponses[keyof RefreshTokenResponses];

export type RevokeRefreshTokenData = {
    body: RefreshTokenDto;
    path?: never;
    query?: never;
    url: '/auth/revoke';
};

export type RevokeRefreshTokenResponses = {
    204: void;
};

export type RevokeRefreshTokenResponse = RevokeRefreshTokenResponses[keyof RevokeRefreshTokenResponses];

export type RevokeAllRefreshTokensData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/revoke-all';
};

export type RevokeAllRefreshTokensResponses = {
    204: void;
};

export type RevokeAllRefreshTokensResponse = RevokeAllRefreshTokensResponses[keyof RevokeAllRefreshTokensResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetCurrentUserResponses = {
    200: UserResponse;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type GetCurrentUserNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me/nodes';
};

export type GetCurrentUserNodesResponses = {
    200: Array<UserNodeResponse>;
};

export type GetCurrentUserNodesResponse = GetCurrentUserNodesResponses[keyof GetCurrentUserNodesResponses];

export type GetCurrentUserJobsData = {
    body?: never;
    path?: never;
    query?: {
        status?: Array<JobStatus>;
        sort?: 'createdAt' | 'startedAt' | 'finishedAt';
        order?: Order;
        page?: number;
        limit?: number;
    };
    url: '/users/me/jobs';
};

export type GetCurrentUserJobsResponses = {
    200: Array<UserJobsResponse>;
};

export type GetCurrentUserJobsResponse = GetCurrentUserJobsResponses[keyof GetCurrentUserJobsResponses];

export type GetCurrentUserJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/users/me/jobs/{id}';
};

export type GetCurrentUserJobResponses = {
    200: Array<UserJob>;
};

export type GetCurrentUserJobResponse = GetCurrentUserJobResponses[keyof GetCurrentUserJobResponses];

export type CreateNodeData = {
    body: CreateNodeDto;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type CreateNodeResponses = {
    201: CreateNodeResponse;
};

export type CreateNodeResponse2 = CreateNodeResponses[keyof CreateNodeResponses];

export type ResetNodeTokenData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/{id}/reset-token';
};

export type ResetNodeTokenResponses = {
    200: ResetNodeTokenResponse;
};

export type ResetNodeTokenResponse2 = ResetNodeTokenResponses[keyof ResetNodeTokenResponses];

export type GetCurrentNodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me';
};

export type GetCurrentNodeResponses = {
    default: RenderNodeResponse;
};

export type GetCurrentNodeResponse = GetCurrentNodeResponses[keyof GetCurrentNodeResponses];

export type GetNextTaskData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes/me/tasks/next';
};

export type GetNextTaskResponses = {
    /**
     * The task this render node should render next
     */
    200: NextTaskResponse;
    /**
     * There is no task to render at this time
     */
    204: void;
};

export type GetNextTaskResponse = GetNextTaskResponses[keyof GetNextTaskResponses];

export type FinishTaskRenderingData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/upload';
};

export type FinishTaskRenderingErrors = {
    /**
     * The task is not being rendered by this render node or already completed
     */
    409: unknown;
};

export type FinishTaskRenderingResponses = {
    /**
     * URLs to upload the render results to
     */
    200: FinishTaskRenderingResponse;
};

export type FinishTaskRenderingResponse2 = FinishTaskRenderingResponses[keyof FinishTaskRenderingResponses];

export type FinishTaskData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/finish';
};

export type FinishTaskErrors = {
    /**
     * The task can not be finished or required result files are missing
     */
    409: unknown;
};

export type FinishTaskResponses = {
    /**
     * Task marked as completed
     */
    202: unknown;
};

export type ReportTaskProgressData = {
    body: ReportTaskProgressDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/nodes/me/tasks/{id}/progress';
};

export type ReportTaskProgressErrors = {
    /**
     * The task is not assigned to this render node or was cancelled. The render node should stop rendering it.
     */
    409: unknown;
};

export type ReportTaskProgressResponses = {
    /**
     * Task progress updated
     */
    204: void;
};

export type ReportTaskProgressResponse = ReportTaskProgressResponses[keyof ReportTaskProgressResponses];

export type CreateJobData = {
    body: CreateJobDto;
    path?: never;
    query?: never;
    url: '/jobs';
};

export type CreateJobResponses = {
    /**
     * The job was created and scene files can now be uploaded
     */
    201: CreateJobResponse;
};

export type CreateJobResponse2 = CreateJobResponses[keyof CreateJobResponses];

export type StartJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/start';
};

export type StartJobErrors = {
    /**
     * The job is not a draft or required scene files are missing
     */
    409: unknown;
};

export type StartJobResponses = {
    /**
     * The job has been queued
     */
    202: unknown;
};

export type GetJobFileData = {
    body?: never;
    path: {
        id: number;
        file: 'scene' | 'octree' | 'emittergrid';
    };
    query?: never;
    url: '/jobs/{id}/files/{file}';
};

export type GetJobFileErrors = {
    /**
     * The file does not exist
     */
    404: unknown;
};

export type GetJobFileResponses = {
    /**
     * A download URL for the requested file, valid for at least 1 hour
     */
    200: UrlResponse;
};

export type GetJobFileResponse = GetJobFileResponses[keyof GetJobFileResponses];

export type AbortJobData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/abort';
};

export type AbortJobErrors = {
    /**
     * The job does not exist or the user cannot access it
     */
    404: unknown;
    /**
     * The job could not be aborted because it is not queued or running
     */
    409: unknown;
};

export type AbortJobResponses = {
    /**
     * The job was aborted
     */
    204: void;
};

export type AbortJobResponse = AbortJobResponses[keyof AbortJobResponses];

export type GetJobTilesData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/jobs/{id}/tiles';
};

export type GetJobTilesErrors = {
    /**
     * The job does not exist or the user cannot access it
     */
    404: unknown;
};

export type GetJobTilesResponses = {
    /**
     * The tiles sorted by row and then column (i.e. the first tile is top left, the last tile is bottom right)
     */
    200: Array<TileResponse>;
};

export type GetJobTilesResponse = GetJobTilesResponses[keyof GetJobTilesResponses];

export type GetResourcePacksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/resource-packs';
};

export type GetResourcePacksResponses = {
    default: Array<ResourcePackResponse>;
};

export type GetResourcePacksResponse = GetResourcePacksResponses[keyof GetResourcePacksResponses];
